### ISSUE TITLE
get_stats_timewindow invalid for string

### ISSUE THREAD

**Issue by MBalszun** [mbeckersys/MavLogAnalyzer#5]
The template `DataTimeseries` has an implementation of the virtual function `get_stats_timewindow` that doesn't work when the datatype is `std::string` (e.g. because it casts the datatype to double in order to determine min and max). 
With my compiler, this results in a compile time error as soon as a `DataTimeseries<std::string>`  is used (as is e.g. happening in `DialogDataTable::_buildTable`) even if the function itself never gets called. 

Is this only a problem on MSVC? Afaik it shouldn't compile on any toolchain.

**Comment by mbeckersys** [comment]
It is compiling with g++ (which does not mean that this is good). Seems like MSVC is trying to instantiate this, unlike g++.

But actually, the template `DataTimeseries` was never meant for `std::string` (that is what `DataEvent` is for), so this being done in the data dialog, is simply not right. I therefore removed the attempt to dyncast a `Data` to `DataTimeseries<std::string>`. That should fix your issue. 

Thanks for reporting.
